<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div class="container">

	<form action="<?php echo $this->baseUrl ?>/logado/delete" method="post" class="form-signin" role="form">
		<h1><?php echo $this->escape($this->title); ?></h1>
		<h4 id='texto-delete' class="form-signin-heading">Tem certeza que deseja deletar sua conta?</h4> <button class="btn btn-lg btn-danger" type="submit">Sim</button>
	</form>
</div>
<?php echo $this->render('footer.phtml'); ?>