<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>
<h1><?php echo $this->escape($this->title); ?></h1>

<form action="<?php echo $this->baseUrl ?>/logado/edit" method="post">
	<input type='text' name='nome' placeholder='Nome'>
	<input type='text' name='sobrenome' placeholder='Sobrenome'>
	<input type='submit' name='cadastrar' value='Cadastrar'>
</form>

<?php echo $this->render('footer.phtml'); ?>