<div id='menu'>
	<div id='menu-home'>
		<a href='<?php echo $this->baseUrl; ?>/logado/'>Home</a>
	</div>
	<div id='menu-editar'>
		<a href='<?php echo $this->baseUrl; ?>/logado/edit'>Editar Conta</a>
	</div>
	<div id='menu-deletar'>
		<a href='<?php echo $this->baseUrl; ?>/logado/delete'>Deletar Conta</a>
	</div>
	<div id='menu-add-conta'>
		<a href='<?php echo $this->baseUrl; ?>/logado/addconta?T'>Adicionar Finanças</a>
	</div>
	<div id='menu-edit-conta'>
		<a href='<?php echo $this->baseUrl; ?>/logado/editconta'>Editar Finanças</a>
	</div>
	<div id='menu-del-conta'>
		<a href='<?php echo $this->baseUrl; ?>/logado/delconta'>Deletar Finanças</a>
	</div>
	<div id='menu-dashboard'>
		<a href='<?php echo $this->baseUrl; ?>/logado/dashboard'>Dashboard</a>
	</div>
	<div id='menu-logout'>
		<a href='<?php echo $this->baseUrl; ?>/logado/logout'>Logout</a>
	</div>
</div>