<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<div class="navbar-brand" href="#">Controle de Finanças</div>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href='<?php echo $this->baseUrl; ?>/logado/'>Home</a></li>
            <li><a href='<?php echo $this->baseUrl; ?>/logado/edit'>Editar Conta</a></li>
            <li><a href='<?php echo $this->baseUrl; ?>/logado/delete'>Deletar Conta</a></li>
			<li><a href='<?php echo $this->baseUrl; ?>/logado/addconta?T'>Adicionar Finanças</a></li>
			<li><a href='<?php echo $this->baseUrl; ?>/logado/editconta?T'>Editar Finanças</a></li>
			<li><a href='<?php echo $this->baseUrl; ?>/logado/delconta?T'>Deletar Finanças</a></li>
			<li><a href='<?php echo $this->baseUrl; ?>/logado/dashboard'>Dashboard</a></li>
			<li><a href='<?php echo $this->baseUrl; ?>/logado/logout'>Logout</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
</div>